const mongoose = require('mongoose');
const dns = require('dns');
require('dotenv').config();

dns.setDefaultResultOrder('ipv4first');
try {
  dns.setServers(['8.8.8.8', '8.8.4.4']);
} catch (e) {}

const RecentEvent = require('./models/RecentEvent');
const FeaturedStory = require('./models/FeaturedStory');
const Destination = require('./models/Destination');
const Product = require('./models/Product');
const Artist = require('./models/Artist');
const Workshop = require('./models/Workshop');
const ForumPost = require('./models/ForumPost');
const CreatorJob = require('./models/CreatorJob');

const dummyEvents = [
  { title: 'Jaipur Literature Festival 2024', description: "World's largest free literary festival at Diggi Palace.", image: 'https://images.unsplash.com/photo-1471970471555-19d4b113e9ed?auto=format&fit=crop&w=1200&q=80', location: 'Diggi Palace, Jaipur', region: 'Rajasthan', date: new Date('2024-02-01'), category: 'Literature & Arts', link: 'https://jaipurliteraturefestival.org/' },
  { title: 'Kala Ghoda Arts Festival', description: 'Vibrant week-long celebration of art, music, dance, and food in Mumbai.', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80', location: 'Kala Ghoda, Mumbai', region: 'Maharashtra', date: new Date('2024-02-03'), category: 'Visual Arts', link: 'https://kalaghodaassociation.com/' },
  { title: 'Rajasthan International Folk Festival (RIFF)', description: 'Folk music and traditional dance performances at Mehrangarh Fort.', image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80', location: 'Mehrangarh Fort, Jodhpur', region: 'Rajasthan', date: new Date('2024-10-25'), category: 'Folk Music', link: 'https://jodhpurfolkfestival.org/' },
  { title: 'Hornbill Festival', description: 'The Festival of Festivals showcasing tribal traditions of Nagaland.', image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80', location: 'Kisama Heritage Village', region: 'Nagaland', date: new Date('2024-12-01'), category: 'Tribal Culture', link: 'https://hornbillfestival.com/' },
  { title: 'Pushkar Camel & Cultural Fair', description: 'Traditional fair featuring camel trading, folk dance, and sacred rituals.', image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80', location: 'Pushkar Fairgrounds', region: 'Rajasthan', date: new Date('2024-11-20'), category: 'Traditions', link: 'https://www.pushkarcamelfair.com/' },
  { title: 'Surajkund International Crafts Mela', description: 'International crafts fair displaying rural Indian handlooms and handicrafts.', image: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80', location: 'Surajkund, Faridabad', region: 'Haryana', date: new Date('2025-02-02'), category: 'Handicrafts', link: 'https://haryana-tourism.gov.in/' },
  { title: 'Khajuraho Dance Festival', description: 'Classical dance set against floodlit 10th-century temples.', image: 'https://images.unsplash.com/photo-1600011689032-8b628b8a874b?auto=format&fit=crop&w=1200&q=80', location: 'Khajuraho Temples', region: 'Madhya Pradesh', date: new Date('2025-02-20'), category: 'Classical Dance', link: 'https://www.mptourism.com/' },
  { title: 'Rann Utsav Kutch', description: 'White salt desert festival with Kutchi embroidery and folk music.', image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80', location: 'Dhordo, Kutch', region: 'Gujarat', date: new Date('2024-11-10'), category: 'Desert Festival', link: 'https://www.rannutsav.net/' },
  { title: 'Mysore Dasara Heritage Procession', description: 'Grand royal procession of decorated elephants and royal artifacts.', image: 'https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80', location: 'Mysore Palace, Mysuru', region: 'Karnataka', date: new Date('2024-10-12'), category: 'Royal Traditions', link: 'https://mysoredasara.gov.in/' },
  { title: 'Konark Dance & Music Festival', description: 'Classical Odissi and Kathak performances under open skies at Sun Temple.', image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80', location: 'Konark Sun Temple', region: 'Odisha', date: new Date('2024-12-05'), category: 'Classical Music & Dance', link: 'https://odishatourism.gov.in/' },
  { title: 'Chembai Sangeethotsavam', description: '15-day Carnatic music festival honoring Saint Tyagaraja and Chembai Vaidyanatha.', image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1200&q=80', location: 'Guruvayur Temple', region: 'Kerala', date: new Date('2024-11-15'), category: 'Carnatic Music', link: 'https://www.guruvayur.org/' },
  { title: 'Thrissur Pooram Temple Festival', description: 'Massive temple festival featuring caparisoned elephants and traditional Kudamattom.', image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1200&q=80', location: 'Vadakkunnathan Temple', region: 'Kerala', date: new Date('2025-05-08'), category: 'Temple Festival', link: 'https://www.keralatourism.org/' },
  { title: 'Bihu Festival of Assam', description: 'Vibrant spring harvest festival celebrating Assamese agricultural traditions.', image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80', location: 'Guwahati & Lakhimpur', region: 'Assam', date: new Date('2025-04-14'), category: 'Harvest Festival', link: 'https://assamtourism.gov.in/' },
  { title: 'Hemis Monastery Festival', description: 'Sacred Buddhist festival featuring masked Cham dances and thangka scroll displays.', image: 'https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80', location: 'Hemis Monastery, Leh', region: 'Ladakh', date: new Date('2025-06-25'), category: 'Buddhist Rituals', link: 'https://leh.nic.in/' },
  { title: 'Chhath Puja Holy Bath Rituals', description: 'Ancient Vedic festival dedicated to Sun God Surya along river ghats.', image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80', location: 'Ganga Ghats, Patna', region: 'Bihar', date: new Date('2024-11-07'), category: 'Vedic Rituals', link: 'https://bihartourism.gov.in/' },
  { title: 'Pongal Harvest Festival', description: 'Four-day Tamil thanksgiving festival honoring nature, livestock, and harvest.', image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80', location: 'Madurai & Tanjore', region: 'Tamil Nadu', date: new Date('2025-01-14'), category: 'Harvest Traditions', link: 'https://www.tntourism.org/' },
  { title: 'Goa Cultural Carnival', description: 'Centuries-old festive parade featuring vibrant floats and street performances.', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80', location: 'Panaji & Margao', region: 'Goa', date: new Date('2025-03-01'), category: 'Heritage Carnival', link: 'https://goatourism.gov.in/' },
  { title: 'Tarnetar Fair Gujarat', description: 'Traditional matchmaking and folk dance fair celebrated at Trinetreshwar temple.', image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80', location: 'Tarnetar, Surendranagar', region: 'Gujarat', date: new Date('2024-09-08'), category: 'Folk Fair', link: 'https://www.gujarattourism.com/' },
  { title: 'Ziro Festival of Music', description: 'Outdoor independent folk and music festival hosted in the lush Ziro Valley.', image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80', location: 'Ziro Valley', region: 'Arunachal Pradesh', date: new Date('2024-09-26'), category: 'Music & Eco Culture', link: 'https://zirofestival.com/' },
  { title: 'Losar Buddhist New Year', description: 'Tibetan New Year marked by traditional ceremonies, prayer flags, and family feasts.', image: 'https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80', location: 'Tabo Monastery, Spiti', region: 'Himachal Pradesh', date: new Date('2025-02-28'), category: 'Buddhist Traditions', link: 'https://himachaltourism.gov.in/' }
];

const dummyStories = [
  { title: "The Last Weavers of Banaras: Threads of Gold & Heritage", description: "Ancient art of Banarasi silk handloom weaving and Kadwa techniques.", content: "For over five centuries, Varanasi has been the beating heart of India royal silk weaving...", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Uttar Pradesh", author: "Priya Sharma", authorRole: "Senior Cultural Documentarian", readTime: "5 min read", link: 'https://www.nationalgeographic.com/', upvotes: 342 },
  { title: "Kathakali: The Divine Sacred Mask of Malabar", description: "Intense facial makeup, mudras, and epic storytelling of Kerala dance-drama.", content: "Before dawn break in the temples of Thrissur, Kathakali dancers sit in solemn silence...", image: "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1200&q=80", category: "dance", region: "Kerala", author: "Rajesh Menon", authorRole: "Folklorist & Researcher", readTime: "7 min read", link: 'https://www.keralatourism.org/', upvotes: 512 },
  { title: "Warli Tribal Murals: Geometry of Sacred Harmony", description: "Sacred wall paintings of the Warli tribe in Maharashtra.", content: "Unlike courtly Indian miniatures, Warli paintings celebrate rhythmic harmony...", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Maharashtra", author: "Sunita Patil", authorRole: "Indigenous Art Curator", readTime: "4 min read", link: 'https://www.culturalindia.net/', upvotes: 289 },
  { title: "The Ancient Culinary Secrets of Chettinad Spices", description: "Grand heritage mansions of Tamil Nadu and stone-ground spices.", content: "Chettinad cuisine is far more than spicy food—it is an intricate culinary architecture...", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80", category: "food", region: "Tamil Nadu", author: "Ananya Sundaram", authorRole: "Culinary Historian", readTime: "6 min read", link: 'https://www.britannica.com/', upvotes: 410 },
  { title: "Pashmina Weavers of Kashmir: The Fine Loom Legacy", description: "High-altitude Changthangi goat wool hand-spun in Srinagar old quarters.", content: "At 14,000 feet in Changthang, nomadic herders collect undercoat wool...", image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Jammu & Kashmir", author: "Tariq Bhat", authorRole: "Textile Researcher", readTime: "8 min read", link: 'https://jktourism.jk.gov.in/', upvotes: 620 },
  { title: "Kanchipuram Silk: The Sacred Korvai Weaving Technique", description: "Temple city weaving where body and border are joined seamlessly.", content: "In Kanchipuram, silk sarees are woven using three shuttles...", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Tamil Nadu", author: "Bhavani Amma", authorRole: "Master Shilp Guru", readTime: "6 min read", link: 'https://www.tntourism.org/', upvotes: 495 },
  { title: "Kalamkari Hand-block Art of Andhra Pradesh", description: "Srikalahasti bamboo pen drawing and organic vegetable dye bath processing.", content: "Kalamkari art dates back to ancient temple banners...", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Andhra Pradesh", author: "K. V. Gurappa", authorRole: "Heritage Master", readTime: "5 min read", link: 'https://aptourism.gov.in/', upvotes: 380 },
  { title: "Tanjore Gold Foil Paintings: Divine Radiant Icons", description: "16th-century courtly paintings crafted with 22K gold leaf and semiprecious stones.", content: "Tanjore paintings feature rich flat colors and embossed gold foil work...", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Tamil Nadu", author: "Raja Rajan", authorRole: "Iconographer", readTime: "7 min read", link: 'https://www.tntourism.org/', upvotes: 510 },
  { title: "Phulkari Floral Embroidery of Punjab Villages", description: "Generational wedding shawls embroidered with bright silk threads on coarse khaddar.", content: "Phulkari literally translates to floral work...", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Punjab", author: "Sanjeev Kaur", authorRole: "Folk Textile Specialist", readTime: "4 min read", link: 'https://punjabtourism.gov.in/', upvotes: 295 },
  { title: "Chamba Rumal Needlework: Double-Sided Silk Embroidery", description: "Miniature painting translated into silk thread using Dorukha stitch.", content: "Hailing from Chamba valley, these embroidered cloths look identical from front and back...", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Himachal Pradesh", author: "Lalit Sharma", authorRole: "Himalayan Art Historian", readTime: "5 min read", link: 'https://himachaltourism.gov.in/', upvotes: 315 },
  { title: "Gond Art of Madhya Pradesh: Sacred Lines of Nature", description: "Indigenous Gond tribal paintings celebrating flora, fauna, and cosmic myths.", content: "Gond artists believe that viewing good images brings good luck...", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Madhya Pradesh", author: "Anupa Shyam", authorRole: "Tribal Art Researcher", readTime: "6 min read", link: 'https://www.mptourism.com/', upvotes: 430 },
  { title: "Pattachitra Palm Leaf Scroll Etching of Odisha", description: "Etching mythological tales onto dried palm leaves using sharp steel styluses.", content: "Raghurajpur heritage village is home to centuries of palm leaf engravers...", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Odisha", author: "Rabindra Behera", authorRole: "Palm Scroll Master", readTime: "5 min read", link: 'https://odishatourism.gov.in/', upvotes: 470 },
  { title: "Channapatna Lacquer Toys: Eco-Friendly Wood turning", description: "Karnataka traditional wooden toys turned on manual lathes and dyed with turmeric.", content: "Originated during the reign of Tipu Sultan who invited Persian craftsmen...", image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", category: "handicrafts", region: "Karnataka", author: "Devendra Kumar", authorRole: "Woodcraft Guild Lead", readTime: "4 min read", link: 'https://www.karnatakatourism.org/', upvotes: 260 },
  { title: "Jaipur Royal Blue Pottery: Quartz Sand & Cobalt Glaze", description: "Turquoise glazed pottery introduced to Rajasthan by Turko-Persian potters.", description: "Blue Pottery is unique because it uses quartz stone powder instead of traditional clay...", image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", category: "handicrafts", region: "Rajasthan", author: "Kripal Kumbhar", authorRole: "Ceramic Historian", readTime: "5 min read", link: 'https://www.tourism.rajasthan.gov.in/', upvotes: 390 },
  { title: "Kasuti Geometric Embroidery of Karnataka", description: "Counting threads to embroider chariot motifs without tying knots on fabric back.", content: "Kasuti involves intricate hand stitches such as Gavanti and Murgi...", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Karnataka", author: "Surekha Kulkarni", authorRole: "Textile Archivist", readTime: "6 min read", link: 'https://www.karnatakatourism.org/', upvotes: 340 },
  { title: "Chanderi Weaving: Lightweight Silk Cotton Sheer", description: "Weaving fine silk cotton gossamer fabric with golden zari brocade borders.", content: "Chanderi fabric has been patronized by Scindia royalty since the 13th century...", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Madhya Pradesh", author: "Mohd. Saeed", authorRole: "Chanderi Loom Master", readTime: "5 min read", link: 'https://www.mptourism.com/', upvotes: 415 },
  { title: "Pochampally Ikkat: Geometric Resist Dyeing", description: "Double-ikkat weaving where warp and weft yarns are tie-dyed before weaving.", content: "Pochampally ikkat in Telangana is famous for mathematical precision in dye resists...", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Telangana", author: "Narasimha Chary", authorRole: "Ikkat Specialist", readTime: "6 min read", link: 'https://telanganatourism.gov.in/', upvotes: 385 },
  { title: "Kantha Quilting Stitch of Bengal", description: "Transforming vintage sarees into embroidered quilts using simple running stitches.", content: "Kantha is a traditional form of rural Bengali embroidery that reuses soft cotton cloth...", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", category: "art", region: "West Bengal", author: "Arundhati Roy", authorRole: "Folklorist", readTime: "4 min read", link: 'https://wbtourism.gov.in/', upvotes: 310 },
  { title: "Cheriyal Nakashi Scroll Paintings of Telangana", description: "Narrative scroll paintings painted on canvas treated with tamarind seed paste.", content: "Cheriyal scrolls depict stories from Indian epics performed by balladeers...", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Telangana", author: "Dhanalakshmi Nakashi", authorRole: "Scroll Painter", readTime: "5 min read", link: 'https://telanganatourism.gov.in/', upvotes: 275 },
  { title: "Kutch Rabari Mirrorwork Embroidery", description: "Nomadic Rabari tribe mirror embroidery protecting against desert elements.", content: "Kutchi Rabari embroidery features small glass mirrors held by intricate chain stitches...", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", category: "art", region: "Gujarat", author: "Radhabai Rabari", authorRole: "Tribal Artisan Lead", readTime: "6 min read", link: 'https://www.gujarattourism.com/', upvotes: 530 }
];

const dummyDestinations = [
  { name: "Khajuraho Temples", englishName: "Khajuraho Group of Monuments", description: "10th-century Nagara-style stone temples celebrated for sculptural detail.", image: "https://images.unsplash.com/photo-1600011689032-8b628b8a874b?auto=format&fit=crop&w=1200&q=80", region: "Madhya Pradesh", lat: 24.8318, lng: 79.9199, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Kandariya Mahadeva Temple", "Light & Sound Show", "Annual Dance Festival"] },
  { name: "Hampi Sacred Ruins", englishName: "Hampi Vijayanagara Capital", description: "Surreal boulder-strewn landscape preserving Vijayanagara stone chariot.", image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", region: "Karnataka", lat: 15.3350, lng: 76.4600, heritage: "UNESCO World Heritage Site", bestTime: "November to February", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Vittala Temple Stone Chariot", "Virupaksha Shrine", "Tungabhadra River Sunset"] },
  { name: "Konark Sun Temple", englishName: "Black Pagoda of Konark", description: "13th-century stone chariot of Sun God Surya with 24 carved wheels.", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80", region: "Odisha", lat: 19.8876, lng: 86.0945, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Stone Sundial Wheels", "Nata Mandap Sculptures", "Chandrabhaga Beach"] },
  { name: "Ajanta Rock-Cut Caves", englishName: "Ajanta Buddhist Caves", description: "30 rock-cut Buddhist cave monuments featuring ancient mural frescoes.", image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80", region: "Maharashtra", lat: 20.5519, lng: 75.7033, heritage: "UNESCO World Heritage Site", bestTime: "November to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Padmapani Mural", "Cave 19 Stupa Hall", "Waghora River Gorge"] },
  { name: "Mahabalipuram Shore Temples", englishName: "Monuments at Mahabalipuram", description: "7th-century Pallava dynasty rock-cut cave sanctuaries and shore temples.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80", region: "Tamil Nadu", lat: 12.6269, lng: 80.1927, heritage: "UNESCO World Heritage Site", bestTime: "November to February", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Arjuna's Penance Relief", "Shore Temple", "Five Rathas Monoliths"] },
  { name: "Meenakshi Amman Temple", englishName: "Madurai Meenakshi Temple", description: "Historic Dravidian temple complex featuring 14 gateway gopurams.", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", region: "Tamil Nadu", lat: 9.9195, lng: 78.1193, heritage: "National Heritage Monument", bestTime: "October to March", entryFee: "Free Entry", highlights: ["1000 Pillar Hall", "Golden Lotus Tank", "Night Ritual Procession"] },
  { name: "Golden Temple Harmandir Sahib", englishName: "Sri Harmandir Sahib", description: "Holiest gurdwara of Sikhism gilded in pure gold surrounded by Amrit Sarovar.", image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80", region: "Punjab", lat: 31.6200, lng: 74.8765, heritage: "Sacred World Heritage Monument", bestTime: "October to March", entryFee: "Free Entry", highlights: ["Golden Sanctum", "Langar Kitchen", "Amrit Sarovar Pool"] },
  { name: "Sanchi Buddhist Stupa", englishName: "Great Stupa at Sanchi", description: "3rd-century BCE Buddhist monument commissioned by Emperor Ashoka.", image: "https://images.unsplash.com/photo-1600011689032-8b628b8a874b?auto=format&fit=crop&w=1200&q=80", region: "Madhya Pradesh", lat: 23.4793, lng: 77.7397, heritage: "UNESCO World Heritage Site", bestTime: "November to February", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Carved Torana Gateways", "Ashoka Pillar Base", "Buddhist Museum"] },
  { name: "Mehrangarh Fort Jodhpur", englishName: "Mehrangarh Citadel", description: "Imposing 15th-century desert fortress towering 400 feet above Jodhpur city.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80", region: "Rajasthan", lat: 26.2978, lng: 73.0185, heritage: "Heritage Royal Fort", bestTime: "October to March", entryFee: "₹100 (Indian), ₹600 (Foreign)", highlights: ["Sheesh Mahal Mirror Room", "Phool Mahal Court", "Folk Musician Courtyard"] },
  { name: "Bodh Gaya Mahabodhi Temple", englishName: "Mahabodhi Temple Complex", description: "Sacred location where Lord Buddha attained enlightenment under the Bodhi Tree.", image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", region: "Bihar", lat: 24.6960, lng: 84.9914, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "Free Entry", highlights: ["Sacred Bodhi Tree", "Vajrasana Diamond Throne", "55m Pyramid Spire"] },
  { name: "Rani ki Vav Stepwell", englishName: "Queen's Stepwell Patan", description: "11th-century subterranean stepwell designed as an inverted temple.", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", region: "Gujarat", lat: 23.8589, lng: 72.1018, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["7 Terraced Levels", "500 Vishnu Sculptures", "Saraswati River Bank"] },
  { name: "Brihadeeswarar Temple Tanjore", englishName: "Great Living Chola Temple", description: "11th-century granite temple built by Emperor Raja Raja Chola I.", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", region: "Tamil Nadu", lat: 10.7828, lng: 79.1318, heritage: "UNESCO World Heritage Site", bestTime: "November to February", entryFee: "Free Entry", highlights: ["80-Ton Granite Dome", "Monolithic Nandi Bull", "Chola Wall Frescoes"] },
  { name: "Chittorgarh Fort Citadel", englishName: "Chittor Hill Fort", description: "Largest fort in India spanning 700 acres celebrating Rajput valor.", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80", region: "Rajasthan", lat: 24.8879, lng: 74.6454, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Vijay Stambha Tower", "Kirti Stambha", "Padmini Palace Reservoir"] },
  { name: "Majuli River Island", englishName: "Majuli Island Assam", description: "World's largest inhabited river island and center of Neo-Vaishnavite Satra culture.", image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80", region: "Assam", lat: 26.9500, lng: 94.1667, heritage: "Cultural Eco Island", bestTime: "October to March", entryFee: "Free Entry", highlights: ["Garamur Satra Monastery", "Traditional Mask Making", "Brahmaputra Sunset"] },
  { name: "Dholavira Harappan City", englishName: "Dholavira Ancient Metropolis", description: "5,000-year-old Indus Valley Civilization city featuring advanced urban water management.", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", region: "Gujarat", lat: 23.8860, lng: 70.2180, heritage: "UNESCO World Heritage Site", bestTime: "November to February", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Stone Reservoirs", "Harappan Signboard", "Acropolis Citadel"] },
  { name: "Ellora Rock-Cut Monasteries", englishName: "Ellora Caves Complex", description: "34 rock-cut caves carved out of Charanandri Hills representing Hindu, Buddhist, and Jain faiths.", image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80", region: "Maharashtra", lat: 20.0268, lng: 75.1774, heritage: "UNESCO World Heritage Site", bestTime: "November to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Kailash Temple Monolith", "Cave 10 Carpenter's Cave", "Jain Indra Sabha"] },
  { name: "Pattadakal Temple Complex", englishName: "Pattadakal Monument Group", description: "8th-century Badami Chalukya temple cluster blending Nagara and Dravidian architecture.", image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", region: "Karnataka", lat: 15.9486, lng: 75.8156, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Virupaksha Temple", "Mallikarjuna Shrine", "Malaprabha River View"] },
  { name: "Nalanda Ancient University", englishName: "Nalanda Mahavihara", description: "5th-century ancient Buddhist monastery university site that attracted international scholars.", image: "https://images.unsplash.com/photo-1600011689032-8b628b8a874b?auto=format&fit=crop&w=1200&q=80", region: "Bihar", lat: 25.1357, lng: 85.4452, heritage: "UNESCO World Heritage Site", bestTime: "October to March", entryFee: "₹40 (Indian), ₹600 (Foreign)", highlights: ["Sariputta Stupa", "Red Brick Monastery Cells", "Nalanda Museum"] },
  { name: "Kaziranga Cultural Buffer", englishName: "Kaziranga Heritage Zone", description: "Assamese tribal villages showcasing Mishing weaving and traditional Bihu folklore.", image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80", region: "Assam", lat: 26.5775, lng: 93.1711, heritage: "UNESCO World Heritage Site", bestTime: "November to April", entryFee: "₹100 (Indian), ₹750 (Foreign)", highlights: ["Orchid Heritage Park", "Mishing Tribal Houses", "Brahmaputra Safari"] },
  { name: "Seringapatam Island Fort", englishName: "Srirangapatna Heritage Citadel", description: "River island fortress town of Hyder Ali and Tipu Sultan on the Cauvery River.", image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", region: "Karnataka", lat: 12.4237, lng: 76.6829, heritage: "Historical Island Monument", bestTime: "October to March", entryFee: "₹25 (Indian), ₹300 (Foreign)", highlights: ["Daria Daulat Palace", "Ranganathaswamy Temple", "Tipu Death Place Monument"] }
];

const dummyProducts = [
  { title: "Handcrafted Madhubani Painting on Raw Silk", description: "Authentic handmade Madhubani folk artwork created using natural vegetable dyes.", price: 3499, originalPrice: 4500, category: "Paintings", craftType: "Madhubani Art", region: "Bihar", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", artisanName: "Sita Devi & Family", rating: 4.9, stock: 8, highlights: ["100% Hand-painted", "Natural Mineral Dyes", "Certificate Included"] },
  { title: "Royal Blue Banarasi Zari Silk Stole", description: "Exquisite handwoven Banarasi stole featuring traditional Kadwa motifs.", price: 4850, originalPrice: 6200, category: "Textiles", craftType: "Banarasi Handloom", region: "Uttar Pradesh", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", artisanName: "Mohd. Umer Loom Crafts", rating: 5.0, stock: 5, highlights: ["Pure Mulberry Silk", "Handloom Weave", "GI Tagged Craft"] },
  { title: "Authentic Dhokra Cast Bronze Peacock Sculpture", description: "Traditional tribal lost-wax bronze casting crafted by indigenous artisans.", price: 2790, originalPrice: 3500, category: "Handicrafts", craftType: "Dhokra Metal Craft", region: "Chhattisgarh", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", artisanName: "Ramesh Jhara", rating: 4.8, stock: 12, highlights: ["4000-Year-Old Technique", "Solid Bell Metal", "Unique Piece"] },
  { title: "Authentic Pashmina Sozni Embroidered Shawl", description: "Pure Kashmir Changthangi cashmere hand-spun and embroidered with needlework.", price: 12500, originalPrice: 15800, category: "Textiles", craftType: "Kashmir Pashmina", region: "Jammu & Kashmir", image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", artisanName: "Tariq Ahmed & Sons", rating: 5.0, stock: 3, highlights: ["100% Cashmere Wool", "Fine Sozni Embroidery", "Hand-spun & Handwoven"] },
  { title: "Channapatna Lacquered Wooden Elephant Pair", description: "Non-toxic wooden toys turned on manual lathes and polished with natural lac dye.", price: 1850, originalPrice: 2400, category: "Handicrafts", craftType: "Channapatna Craft", region: "Karnataka", image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", artisanName: "Shivalingappa Crafts", rating: 4.9, stock: 15, highlights: ["Non-toxic Eco Paint", "Wrightia Tinctoria Wood", "GI Tagged Craft"] },
  { title: "Tanjore 22K Gold Foil Saraswati Painting", description: "Classic South Indian relief painting crafted with teak wood frame and 22K gold foil.", price: 18900, originalPrice: 24000, category: "Paintings", craftType: "Tanjore Gold Painting", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", artisanName: "Raja Rajan Studios", rating: 5.0, stock: 2, highlights: ["Genuine 22K Gold Leaf", "Jaipur Gemstones", "Teak Wood Frame"] },
  { title: "Pure Kanchipuram Handloom Silk Saree", description: "Heavy silk saree woven with contrasting temple zari border using Korvai technique.", price: 21500, originalPrice: 28000, category: "Textiles", craftType: "Kanchipuram Silk", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80", artisanName: "Bhavani Amma Crafts", rating: 5.0, stock: 4, highlights: ["Pure Mulberry Silk", "3-Shuttle Korvai Weave", "GI Certified Saree"] },
  { title: "Bankura Terracotta Sacred Panchmura Horse Pair", description: "Traditional terracotta horses crafted with distinct long ears and natural red clay.", price: 2950, originalPrice: 3800, category: "Pottery", craftType: "Bankura Terracotta", region: "West Bengal", image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", artisanName: "Bankura Clay Guild", rating: 4.9, stock: 10, highlights: ["Hand-turned Clay", "Panchmura Artisan Village", "GI Tagged Terracotta"] },
  { title: "Tree of Life Kalamkari Hand-drawn Tapestry", description: "Freehand bamboo pen drawing on unbleached cotton processed with vegetable dyes.", price: 4200, originalPrice: 5500, category: "Paintings", craftType: "Kalamkari Art", region: "Andhra Pradesh", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", artisanName: "Gurappa Chetty", rating: 4.9, stock: 6, highlights: ["100% Organic Dyes", "Srikalahasti Style", "Bamboo Pen Work"] },
  { title: "Jaipur Royal Blue Pottery Decorative Vase", description: "Turquoise glazed quartz vase hand-painted with Persian floral motifs.", price: 2450, originalPrice: 3200, category: "Pottery", craftType: "Jaipur Blue Pottery", region: "Rajasthan", image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", artisanName: "Kripal Kumbhar Studio", rating: 4.8, stock: 9, highlights: ["Quartz Glass Powder", "Cobalt Blue Glaze", "Hand-painted Floral"] },
  { title: "Bidriware Pure Silver Inlay Brass Jewelry Box", description: "Zinc-copper alloy vessel inlaid with pure silver wire sheets and blackened with soil.", price: 5600, originalPrice: 7200, category: "Handicrafts", craftType: "Bidriware Craft", region: "Karnataka", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", artisanName: "Bidar Silver Guild", rating: 5.0, stock: 4, highlights: ["99.9% Pure Silver Inlay", "Blackened Zinc Alloy", "GI Tagged Craft"] },
  { title: "Odisha Pattachitra Palm Leaf Engraving Art", description: "Etched dried palm leaf scroll bound with red silk thread depicting Lord Jagannath.", price: 3800, originalPrice: 4900, category: "Paintings", craftType: "Pattachitra Art", region: "Odisha", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", artisanName: "Rabindra Behera", rating: 4.9, stock: 7, highlights: ["Steel Needle Etched", "Natural Lampblack Pigment", "Raghurajpur Heritage"] },
  { title: "Phulkari Silk Embroidered Chiffon Dupatta", description: "Bright yellow chiffon dupatta embroidered with geometric garden silk stitches.", price: 3200, originalPrice: 4200, category: "Textiles", craftType: "Phulkari Craft", region: "Punjab", artisanName: "Sanjeev Kaur Guild", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", rating: 4.8, stock: 11, highlights: ["Hand-embroidered Silk", "Traditional Bagh Motif", "Lightweight Festive Wear"] },
  { title: "Chanderi Tissue Silk Saree with Zari Border", description: "Gossamer sheer silk cotton saree woven with fine gold zari floral buttis.", price: 8900, originalPrice: 11500, category: "Textiles", craftType: "Chanderi Weave", region: "Madhya Pradesh", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", artisanName: "Mohd. Saeed Looms", rating: 4.9, stock: 5, highlights: ["Lightweight Silk Cotton", "Real Metallic Zari", "Scindia Royal Loom"] },
  { title: "Cheriyal Hand-painted Wooden Mask Artifact", description: "Traditional folk mask crafted from tamarind seed paste, sawdust, and natural dyes.", price: 2100, originalPrice: 2800, category: "Handicrafts", craftType: "Cheriyal Craft", region: "Telangana", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", artisanName: "Dhanalakshmi Studio", rating: 4.7, stock: 14, highlights: ["Eco Sawdust Mold", "Folk Mythological Icon", "GI Tagged Telangana Craft"] },
  { title: "Gond Indigenous Art Canvas Painting", description: "Fine line dot-work painting depicting forest wildlife and sacred trees.", price: 4600, originalPrice: 6000, category: "Paintings", craftType: "Gond Tribal Art", region: "Madhya Pradesh", image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", artisanName: "Anupa Shyam", rating: 4.9, stock: 6, highlights: ["Intricate Dot Technique", "Archival Canvas", "Signed by Tribal Master"] },
  { title: "Kasuti Geometric Hand Embroidered Silk Dupatta", description: "Traditional Karnataka needlework featuring Gavanti and Murgi unknotted stitches.", price: 3900, originalPrice: 5100, category: "Textiles", craftType: "Kasuti Embroidery", region: "Karnataka", image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", artisanName: "Surekha Kulkarni", rating: 4.9, stock: 8, highlights: ["Hand-counted Stitching", "Pure Raw Silk", "No Fabric Back Knots"] },
  { title: "Traditional Brass Uruli Water Vessel with Handles", description: "Heavy cast brass water vessel for floating flowers and ritual incense.", price: 3450, originalPrice: 4400, category: "Handicrafts", craftType: "Brass Metalwork", region: "Kerala", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", artisanName: "Mannar Metal Guild", rating: 5.0, stock: 9, highlights: ["100% Solid Brass", "Traditional Pit Cast", "High Polish Finish"] },
  { title: "Handcrafted Brass Temple Diya Lamp", description: "Ornate multi-tier peacock oil lamp cast in solid bell metal.", price: 2850, originalPrice: 3600, category: "Handicrafts", craftType: "Temple Metalwork", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", artisanName: "Swamimalai Bronze Works", rating: 4.9, stock: 12, highlights: ["Solid Bell Brass", "Swamimalai Casting", "Traditional Peacock Top"] },
  { title: "Kutch Mirrorwork Hand-stitched Cushion Cover Pair", description: "Vibrant cotton cushion covers featuring Rabari mirrorwork and tassel trim.", price: 1650, originalPrice: 2200, category: "Textiles", craftType: "Kutch Mirrorwork", region: "Gujarat", image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", artisanName: "Radhabai Rabari", rating: 4.8, stock: 18, highlights: ["Real Glass Mirrors", "Nomadic Hand-stitch", "100% Organic Cotton"] }
];

const dummyArtists = [
  { name: "Master Rameshwar Paswan", craft: "Madhubani & Mithila Painting", region: "Madhubani, Bihar", bio: "Carrying forward a 4-generation legacy of Mithila wall painting.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 32, rating: 4.9, specialties: ["Kohbar Motifs", "Natural Pigments", "Silk Painting"], story: "Every line in Madhubani is a prayer for peace." },
  { name: "Gurumayi Bhavani Amma", craft: "Kanchipuram Silk Weaving", region: "Kanchipuram, Tamil Nadu", bio: "Shilp Guru awardee known for her intricate Korvai weaving technique.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80", experienceYears: 45, rating: 5.0, specialties: ["Korvai Technique", "Temple Zari Borders", "Silk Dyeing"], story: "A true Kanchipuram saree stays radiant for three generations." },
  { name: "Ustad Mohsin Khan", craft: "Banarasi Handloom Weaving", region: "Varanasi, Uttar Pradesh", bio: "Master weaver carrying forward 300 years of royal family looms.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80", experienceYears: 38, rating: 4.9, specialties: ["Kadwa Weave", "Real Zari Work", "Tanchoi Silk"], story: "We are weaving poetry into silk on our looms." },
  { name: "Ramesh Jhara", craft: "Dhokra Lost-Wax Metal Casting", region: "Bastar, Chhattisgarh", bio: "Preserving 4,000-year-old indigenous lost-wax bronze metal techniques.", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80", experienceYears: 28, rating: 4.8, specialties: ["Lost-Wax Casting", "Beeswax Threading", "Bell Metal"], story: "Each metal figurine is made from a wax mold that melts in the fire." },
  { name: "Rabindra Behera", craft: "Pattachitra Palm Leaf Etching", region: "Raghurajpur, Odisha", bio: "National Awardee palm leaf engraver from Raghurajpur heritage village.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 35, rating: 4.9, specialties: ["Palm Leaf Etching", "Natural Charcoal Dye", "Mythological Scrolls"], story: "Etching on dried palm leaf requires unwavering hand focus." },
  { name: "Prakash Maharaj", craft: "Kathakali Performance & Makeup", region: "Thrissur, Kerala", bio: "Master Kathakali artiste and vesicular stone makeup expert.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80", experienceYears: 30, rating: 5.0, specialties: ["Chutti Makeup", "Navarasas", "Temple Mudras"], story: "The makeup ritual transforms the performer into divine energy." },
  { name: "Mansukhbhai Prajapati", craft: "Terracotta Clay Sculpture", region: "Wankaner, Gujarat", bio: "Innovator in earthenware terracotta pots and traditional claycraft.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 26, rating: 4.9, specialties: ["Red Clay Turning", "Pit-Firing", "Earthen Utensils"], story: "Clay is alive; it responds to gentle pressure on the wheel." },
  { name: "Sitaram Warli", craft: "Warli Tribal Painting", region: "Palghar, Maharashtra", bio: "Indigenous Warli elder maintaining ritual wall murals.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80", experienceYears: 40, rating: 4.8, specialties: ["Rice Paste Murals", "Tarpa Dance Motifs", "Harvest Canvas"], story: "Our paintings honor mother earth and the cycle of seasons." },
  { name: "Ghulam Hassan Bhat", craft: "Pashmina Sozni Embroidery", region: "Srinagar, Jammu & Kashmir", bio: "Senior Kashmir artisan specializing in needlework Pashmina shawls.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 34, rating: 5.0, specialties: ["Sozni Needlework", "Kani Loom Shawls", "Walnut Dye"], story: "A fine Pashmina needlework shawl is a labor of love taking months." },
  { name: "K. V. Gurappa", craft: "Kalamkari Pen Art", region: "Srikalahasti, Andhra Pradesh", bio: "Living master of bamboo pen drawing and organic vegetable dye baths.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80", experienceYears: 42, rating: 4.9, specialties: ["Bamboo Kalam Pen", "Myrobalan Mordant", "Tree of Life"], story: "We draw divine epics using natural bamboo pens and plant dyes." },
  { name: "Lakshmi Devi Tanjore", craft: "Tanjore Gold Foil Painting", region: "Thanjavur, Tamil Nadu", bio: "Master painter specializing in 22K gold leaf iconography.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80", experienceYears: 31, rating: 5.0, specialties: ["22K Gold Foil", "Relief Gesso Work", "Teak Frames"], story: "Gold foil work gives eternal radiance to sacred Tanjore icons." },
  { name: "Mohammad Yasin Weaver", craft: "Chanderi Gossamer Loom", region: "Chanderi, Madhya Pradesh", bio: "Third-generation silk-cotton Chanderi loom specialist.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 27, rating: 4.8, specialties: ["Tissue Silk", "Zari Buttass", "Manual Pit Loom"], story: "Chanderi sheer fabric feels as light as air." },
  { name: "Anupa Gond", craft: "Gond Tribal Canvas Art", region: "Dindori, Madhya Pradesh", bio: "Renowned female Gond painter exhibiting indigenous mythologies.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80", experienceYears: 22, rating: 4.9, specialties: ["Line & Dot Patterns", "Natural Mineral Pigments", "Forest Lore"], story: "Every animal and tree has a sacred soul in Gond folklore." },
  { name: "Devendra Kumar Channapatna", craft: "Lacquered Wood Toy Craft", region: "Channapatna, Karnataka", bio: "President of Channapatna Crafts Guild promoting eco wooden toys.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80", experienceYears: 29, rating: 4.9, specialties: ["Natural Vegetable Lac", "Wrightia Wood Turning", "Eco Toys"], story: "Our wooden toys are safe for children and gentle on the planet." },
  { name: "Surekha Kasuti", craft: "Kasuti Needlework", region: "Dharwad, Karnataka", bio: "Archivist and master trainer in traditional unknotted Kasuti stitches.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80", experienceYears: 33, rating: 4.9, specialties: ["Gavanti Stitch", "Murgi Stitch", "Thread Count Embroidery"], story: "Kasuti requires counting threads to create reversible patterns." },
  { name: "Sanjeev Phulkari", craft: "Phulkari Bagh Embroidery", region: "Patiala, Punjab", bio: "Preserving antique Bagh embroidery motifs passed down by grandmothers.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 25, rating: 4.8, specialties: ["Silk Darning Stitch", "Khaddar Canvas", "Wedding Bagh"], story: "Phulkari is a celebration of joy and color embroidered by hand." },
  { name: "Bhaskar Chitrakar", craft: "Kalighat Pat Painting", region: "Kolkata, West Bengal", bio: "Kalighat pat artist depicting traditional socio-cultural watercolor scrolls.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80", experienceYears: 36, rating: 4.9, specialties: ["Bold Brushstrokes", "Natural Dyes", "Satirical Scrolls"], story: "Kalighat pat art captures the pulse of urban and folk life." },
  { name: "Radhabai Rabari", craft: "Kutchi Rabari Mirrorwork", region: "Anjar, Gujarat", bio: "Nomadic community artisan lead preserving Kutchi mirror embroidery.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80", experienceYears: 39, rating: 5.0, specialties: ["Glass Mirrorwork", "Chain Stitching", "Nomadic Quilts"], story: "Mirrors reflect desert sunlight and ward off evil spirits." },
  { name: "Vasudevan Namboothiri", craft: "Temple Metal Bronze Casting", region: "Swamimalai, Tamil Nadu", bio: "Sthapati sculptor creating lost-wax bronze idols adhering to Shilpa Shastras.", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80", experienceYears: 44, rating: 5.0, specialties: ["Lost-Wax Bronze", "Shilpa Shastra Proportions", "Nataraja Casting"], story: "Ancient bronze icon casting follows strict mathematical proportions." },
  { name: "Parvati Baul", craft: "Baul Mystic Music & Ektara", region: "Birbhum, West Bengal", bio: "Renowned Baul musician and oral tradition practitioner performing worldwide.", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80", experienceYears: 28, rating: 4.9, specialties: ["Ektara Performance", "Duggi Drumming", "Mystic Songs"], story: "Baul music is a journey inward connecting with the supreme soul." }
];

const dummyWorkshops = [
  { title: "Masterclass: Madhubani Folk Art & Natural Dyes", description: "Fundamentals of Mithila painting, cosmic motifs, and extracting colors from turmeric and indigo.", instructor: "Master Rameshwar Paswan", instructorTitle: "National Awardee Artist", category: "Visual Arts", region: "Bihar", duration: "4 Weeks (8 Live Sessions)", difficulty: "Beginner", rating: 4.9, image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", price: 1499, enrolledCount: 380, syllabus: [{ title: "Lesson 1: History of Mithila Paintings & Sacred Symbols", duration: "45 mins" }, { title: "Lesson 2: Preparing Natural Pigments & Bamboo Brushes", duration: "60 mins" }] },
  { title: "Traditional Clay Pottery & Terracotta Sculpting", description: "Clay preparation, wheel throwing, surface etching, and traditional pit-firing methods.", instructor: "Kumbhar Shivalingappa", instructorTitle: "Master Potter", category: "Pottery & Crafts", region: "Karnataka", duration: "2 Weeks", difficulty: "Intermediate", rating: 4.8, image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", price: 999, enrolledCount: 240, syllabus: [{ title: "Lesson 1: Understanding Indian Red Clay & Wedging", duration: "50 mins" }, { title: "Lesson 2: Center & Pulling on the Manual Wheel", duration: "75 mins" }] },
  { title: "Kalamkari Pen Drawing & Natural Block Printing", description: "Srikalahasti style of freehand bamboo pen drawing and organic vegetable dye bath processing.", instructor: "Gurappa Chetty", instructorTitle: "Shilp Guru Awardee", category: "Textiles", region: "Andhra Pradesh", duration: "3 Weeks", difficulty: "Beginner", rating: 5.0, image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", price: 1799, enrolledCount: 410, syllabus: [{ title: "Lesson 1: Preparing Cotton Cloth with Milk Bath", duration: "60 mins" }, { title: "Lesson 2: Bamboo Pen Etching with Myrobalan Dye", duration: "90 mins" }] },
  { title: "Banarasi Handloom Zari Weaving Essentials", description: "Introduction to Jacquard looms, Kadwa weaving techniques, and silver zari threading.", instructor: "Ustad Mohsin Khan", instructorTitle: "Master Loom Weaver", category: "Textiles", region: "Uttar Pradesh", duration: "4 Weeks", difficulty: "Advanced", rating: 4.9, image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", price: 2100, enrolledCount: 310, syllabus: [{ title: "Lesson 1: Setting Warp Threads on Handloom", duration: "60 mins" }] },
  { title: "Pattachitra Palm Leaf Etching & Pigment Extraction", description: "Etching dried palm leaves with steel needles and applying natural lampblack ink.", instructor: "Rabindra Behera", instructorTitle: "Palm Scroll Master", category: "Visual Arts", region: "Odisha", duration: "3 Weeks", difficulty: "Intermediate", rating: 4.9, image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", price: 1599, enrolledCount: 290, syllabus: [{ title: "Lesson 1: Curing & Stitching Palm Leaves", duration: "45 mins" }] },
  { title: "Kathakali Facial Makeup & Mudra Rituals", description: "Applying natural stone Chutti makeup and practicing 24 basic root mudras.", instructor: "Prakash Maharaj", instructorTitle: "Kathakali Artiste", category: "Music & Dance", region: "Kerala", duration: "2 Weeks", difficulty: "Beginner", rating: 5.0, image: "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1200&q=80", price: 1299, enrolledCount: 350, syllabus: [{ title: "Lesson 1: Facial Pigment Mixing & Eye Expression", duration: "60 mins" }] },
  { title: "Tanjore 22K Gold Foil Application Workshop", description: "Relief gesso work, gem setting, and applying authentic 22K gold leaf to wooden panels.", instructor: "Lakshmi Devi Tanjore", instructorTitle: "Iconographer", category: "Visual Arts", region: "Tamil Nadu", duration: "4 Weeks", difficulty: "Advanced", rating: 5.0, image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", price: 2499, enrolledCount: 195, syllabus: [{ title: "Lesson 1: Teak Wood Board Gesso Preparation", duration: "75 mins" }] },
  { title: "Dhokra Lost-Wax Bronze Casting Fundamentals", description: "Sculpting beeswax threads, clay casing, and pit furnace bronze pouring.", instructor: "Ramesh Jhara", instructorTitle: "Tribal Metal Master", category: "Pottery & Crafts", region: "Chhattisgarh", duration: "3 Weeks", difficulty: "Intermediate", rating: 4.8, image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", price: 1699, enrolledCount: 220, syllabus: [{ title: "Lesson 1: Clay Core Formation & Beeswax Wire Wrapping", duration: "90 mins" }] },
  { title: "Warli Rice Paste Wall Painting Techniques", description: "Learning elemental Warli shapes: circles, triangles, and squares on red ochre background.", instructor: "Sitaram Warli", instructorTitle: "Tribal Elder", category: "Visual Arts", region: "Maharashtra", duration: "2 Weeks", difficulty: "Beginner", rating: 4.8, image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80", price: 899, enrolledCount: 460, syllabus: [{ title: "Lesson 1: Red Ochre Canvas & Rice Paste Ink", duration: "45 mins" }] },
  { title: "Kashmir Sozni Needlework Masterclass", description: "Fine needle darning stitches on Changthangi cashmere wool fabric.", instructor: "Ghulam Hassan Bhat", instructorTitle: "Master Embroiderer", category: "Textiles", region: "Jammu & Kashmir", duration: "4 Weeks", difficulty: "Intermediate", rating: 5.0, image: "https://images.unsplash.com/photo-1600100397608-f09074aa882b?auto=format&fit=crop&w=1200&q=80", price: 1899, enrolledCount: 275, syllabus: [{ title: "Lesson 1: Tracing Floral Motifs with Wooden Blocks", duration: "60 mins" }] },
  { title: "Channapatna Toy Turning & Vegetable Lacquer", description: "Manual wood lathe turning and friction lacquering using non-toxic natural colors.", instructor: "Devendra Kumar", instructorTitle: "Craft Guild Lead", category: "Pottery & Crafts", region: "Karnataka", duration: "2 Weeks", difficulty: "Beginner", rating: 4.9, image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", price: 1199, enrolledCount: 310, syllabus: [{ title: "Lesson 1: Wrightia Wood Sanding & Lathe Setup", duration: "50 mins" }] },
  { title: "Phulkari Floral Embroidery Basics", description: "Embroidering geometric floral patterns on khaddar cotton using unspun silk thread.", instructor: "Sanjeev Kaur", instructorTitle: "Folk Textile Lead", category: "Textiles", region: "Punjab", duration: "2 Weeks", difficulty: "Beginner", rating: 4.8, image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", price: 999, enrolledCount: 380, syllabus: [{ title: "Lesson 1: Counting Khaddar Weave Threads", duration: "45 mins" }] },
  { title: "Gond Tribal Canvas Painting & Dot Patterns", description: "Expressing nature lore using signature Gond lines, dots, and natural earth colors.", instructor: "Anupa Gond", instructorTitle: "Tribal Artist", category: "Visual Arts", region: "Madhya Pradesh", duration: "3 Weeks", difficulty: "Beginner", rating: 4.9, image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1200&q=80", price: 1399, enrolledCount: 345, syllabus: [{ title: "Lesson 1: Animal & Tree Line Outlines", duration: "60 mins" }] },
  { title: "Jaipur Blue Pottery Glazing & Firing", description: "Mixing quartz powder dough, hand-molding vases, and firing blue glaze in kilns.", instructor: "Kripal Kumbhar", instructorTitle: "Ceramic Master", category: "Pottery & Crafts", region: "Rajasthan", duration: "3 Weeks", difficulty: "Intermediate", rating: 4.8, image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80", price: 1499, enrolledCount: 260, syllabus: [{ title: "Lesson 1: Quartz Dough Preparation & Mold Pressing", duration: "60 mins" }] },
  { title: "Cheriyal Scroll Mask Painting", description: "Making light wooden masks from sawdust, tamarind seed paste, and tempera paints.", instructor: "Dhanalakshmi Nakashi", instructorTitle: "Scroll Painter", category: "Visual Arts", region: "Telangana", duration: "2 Weeks", difficulty: "Beginner", rating: 4.7, image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=80", price: 1099, enrolledCount: 205, syllabus: [{ title: "Lesson 1: Tamarind Paste Molding & Priming", duration: "50 mins" }] },
  { title: "Carnatic Vocal & Rhythm Tala Basics", description: "Vocal warmups, Svaras, and understanding Adi & Rupaka Talas.", instructor: "Chembai Academy Lead", instructorTitle: "Carnatic Vocalist", category: "Music & Dance", region: "Kerala", duration: "4 Weeks", difficulty: "Beginner", rating: 4.9, image: "https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=1200&q=80", price: 1299, enrolledCount: 420, syllabus: [{ title: "Lesson 1: Sarali Varisai Exercises", duration: "60 mins" }] },
  { title: "Shehnai & Indian Reed Raga Fundamentals", description: "Breath control, finger placement, and playing fundamental Hindustani ragas.", instructor: "Ustad Bismillah Guild", instructorTitle: "Classical Musician", category: "Music & Dance", region: "Uttar Pradesh", duration: "4 Weeks", difficulty: "Intermediate", rating: 4.9, image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80", price: 1799, enrolledCount: 180, syllabus: [{ title: "Lesson 1: Reed Selection & Alankar Practice", duration: "60 mins" }] },
  { title: "Kanchipuram Korvai Silk Joining Technique", description: "Advanced handloom weaving module on interlocking border and body warp threads.", instructor: "Gurumayi Bhavani Amma", instructorTitle: "Shilp Guru", category: "Textiles", region: "Tamil Nadu", duration: "4 Weeks", difficulty: "Advanced", rating: 5.0, image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80", price: 2399, enrolledCount: 165, syllabus: [{ title: "Lesson 1: Dual Shuttle Coordination", duration: "90 mins" }] },
  { title: "Kasuti Reversible Embroidery Stitching", description: "Stitching Gavanti line work and Murgi zig-zag patterns without knotting.", instructor: "Surekha Kasuti", instructorTitle: "Embroidery Lead", category: "Textiles", region: "Karnataka", duration: "2 Weeks", difficulty: "Intermediate", rating: 4.9, image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80", price: 1199, enrolledCount: 295, syllabus: [{ title: "Lesson 1: Grid Mapping on Silk Fabric", duration: "45 mins" }] },
  { title: "Sitar Hindustani Raga Fundamentals", description: "Meend bending, stroke technique (Da & Ra), and playing Raga Bhimpalasi.", instructor: "Pandit Ravi Academy", instructorTitle: "Sitarist", category: "Music & Dance", region: "Delhi", duration: "4 Weeks", difficulty: "Intermediate", rating: 5.0, image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80", price: 1999, enrolledCount: 360, syllabus: [{ title: "Lesson 1: Tuning Sitar & Mizrab Stroke Technique", duration: "60 mins" }] }
];

const dummyForumPosts = [
  { title: "How can we better document vanishing oral folk songs of Central India?", content: "Many traditional harvesting songs exist only in the memories of elders above 70.", author: "Vikramaditya Roy", authorRole: "Ethnomusicologist", category: "Oral Histories", upvotes: 84, tags: ["Folk Songs", "Documentation"], comments: [{ author: "Meera Sen", authorRole: "Audio Archivist", content: "24-bit WAV handheld recorders work best!" }] },
  { title: "Protecting Geographical Indication (GI) tags for regional handicraft artisans", content: "Mill-made replicas hurt authentic weavers. Let's discuss digital QR codes and provenance.", author: "Kabir Das", authorRole: "Craft Advocate", category: "Artisan Welfare", upvotes: 112, tags: ["GI Tag", "Handloom"], comments: [] },
  { title: "Sourcing natural mineral pigments for traditional temple frescoes", content: "Where can independent conservators source authentic lapis lazuli and malachite ground powder?", author: "Ananya Varma", authorRole: "Art Restorer", category: "Craft Techniques", upvotes: 95, tags: ["Fresco", "Natural Dyes"], comments: [] },
  { title: "Audio field recording gear for tribal harvesting rituals in Nagaland", content: "What windscreen mics handle humid mountain valley winds during Hornbill field recordings?", author: "Tariq Ahmed", authorRole: "Sound Engineer", category: "Oral Histories", upvotes: 76, tags: ["Sound", "Field Notes"], comments: [] },
  { title: "Preserving 100-year-old handloom pit looms in Varanasi old quarters", content: "Pit looms carved from teak wood are facing termite decay. What eco-friendly wood preservatives work?", author: "Mohd. Saeed", authorRole: "Master Weaver", category: "Craft Techniques", upvotes: 134, tags: ["Looms", "Varanasi"], comments: [] },
  { title: "Direct-to-consumer e-commerce logistics for rural artisan cooperatives", content: "How can remote village artisan guilds manage eco packaging and international shipping frictionlessly?", author: "Devendra Kumar", authorRole: "Guild Lead", category: "Artisan Welfare", upvotes: 150, tags: ["Fair Trade", "Logistics"], comments: [] },
  { title: "Archiving classical dance mudras in digital 3D motion capture format", content: "Can 3D motion capture preserve subtle hand gestures of Bharatanatyam for future dance academies?", author: "Prakash Maharaj", authorRole: "Dance Artiste", category: "Architecture", upvotes: 88, tags: ["3D", "Mudras"], comments: [] },
  { title: "Reviving ancient natural dye recipes using indigo and madder root", content: "Sharing exact fermentation ratios for organic indigo vats using lime and iron sulfate.", author: "Gurappa Chetty", authorRole: "Kalamkari Master", category: "Craft Techniques", upvotes: 165, tags: ["Indigo", "Dyes"], comments: [] },
  { title: "Fair wages and digital payments for women artisans in Kutchi embroidery", content: "Implementing UPI payment terminals directly in women's weaving self-help groups in Kutch.", author: "Radhabai Rabari", authorRole: "Artisan Lead", category: "Artisan Welfare", upvotes: 140, tags: ["UPI", "Women Crafts"], comments: [] },
  { title: "Traditional rain harvest stepwells (Bawris) as community heritage hubs", content: "Restoring subterranean stepwells in Shekhawati as venues for night folk music concerts.", author: "Sunita Patil", authorRole: "Architect", category: "Architecture", upvotes: 120, tags: ["Stepwells", "Rajasthan"], comments: [] },
  { title: "Preserving palm leaf manuscripts against tropical humidity and insect damage", content: "Traditional lemongrass oil application keeps etched palm leaves pliable for over 200 years.", author: "Rabindra Behera", authorRole: "Palm Scroll Master", category: "Oral Histories", upvotes: 105, tags: ["Palm Leaf", "Conservation"], comments: [] },
  { title: "Teaching traditional puppetry (Kathputli) to school children in cities", content: "How Rajasthan puppet masters are adapting puppet shows to teach environmental conservation.", author: "Lalit Sharma", authorRole: "Educator", category: "Oral Histories", upvotes: 92, tags: ["Puppetry", "Education"], comments: [] },
  { title: "Building community-led eco-museums in Northeast tribal villages", content: "Instead of glass cases in cities, let's keep artifacts in living village eco-museums.", author: "Tariq Bhat", authorRole: "Anthropologist", category: "Artisan Welfare", upvotes: 118, tags: ["Eco Museum", "Northeast"], comments: [] },
  { title: "Challenges in certifying authentic Changthangi Pashmina wool against synthetic blends", content: "Using portable laser spectroscopy to verify pure Pashmina cashmere fibers at local markets.", author: "Ghulam Hassan", authorRole: "Textile Lab Lead", category: "Artisan Welfare", upvotes: 160, tags: ["Pashmina", "GI Tag"], comments: [] },
  { title: "Restoring weathered Tanjore paintings without stripping 22K gold leaf", content: "Gentle cleaning solutions for removing decades of oil soot from temple icons.", author: "Lakshmi Devi", authorRole: "Restoration Lead", category: "Craft Techniques", upvotes: 110, tags: ["Tanjore", "Restoration"], comments: [] },
  { title: "Documenting Baul mystic songs of Bengal before rural melodies fade", content: "Recording wandering Baul minstrels along the Padma river using solar-powered audio rigs.", author: "Parvati Baul", authorRole: "Musician", category: "Oral Histories", upvotes: 145, tags: ["Baul", "Mystic Music"], comments: [] },
  { title: "Ethics of field documentation in indigenous tribal villages", content: "Ensuring proper consent, profit sharing, and credit for tribal storytellers during film shoots.", author: "Priya Sharma", authorRole: "Documentarian", category: "Artisan Welfare", upvotes: 175, tags: ["Ethics", "Field Work"], comments: [] },
  { title: "Filming folk music festivals in remote desert locations", content: "Solar battery management and dust prevention for cameras at the Thar desert RIFF festival.", author: "Rajesh Menon", authorRole: "Filmmaker", category: "Oral Histories", upvotes: 98, tags: ["Filmmaking", "Desert"], comments: [] },
  { title: "Digital archives for ancient Sanskrit dance manuals (Natyashastra)", content: "Digitizing 1,000-year-old palm leaf manuscripts into searchable open-access Sanskrit databases.", author: "Arundhati Roy", authorRole: "Scholar", category: "Oral Histories", upvotes: 130, tags: ["Natyashastra", "Archive"], comments: [] },
  { title: "Crowdfunding heritage restoration for village community shrines", content: "Empowering rural Panchayats to raise funds directly for restoring carved wooden temple doors.", author: "Sitaram Warli", authorRole: "Community Elder", category: "Architecture", upvotes: 155, tags: ["Crowdfunding", "Shrines"], comments: [] }
];

const dummyCreatorJobs = [
  { title: "Cultural Heritage Documentary Grant 2026", organization: "RIWAYAT Preservation Foundation", type: "Grant", grantAmount: "₹2,50,000 per project", region: "Pan-India", deadline: "October 15, 2026", description: "Supporting 10 independent videographers to document craft practices across India.", requirements: ["2 years experience", "Field proposal", "Portfolio submission"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Field Researcher & Folk Lore Archivist", organization: "Indian Heritage Archive Project", type: "Fellowship", grantAmount: "₹45,000 / month", region: "Northeast India", deadline: "November 01, 2026", description: "6-month residency fellowship to record oral narratives and tribal weaving motifs.", requirements: ["Anthropology degree", "Local language skill"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Artisan Photography Commission Grant", organization: "National Craft Council", type: "Commission", grantAmount: "₹1,80,000", region: "Rajasthan & Gujarat", deadline: "December 01, 2026", description: "High-resolution photo documentation of master weavers and potters in rural workshops.", requirements: ["DSLR portfolio", "Travel readiness"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Indigenous Craft Videography Fellowship", organization: "Living Traditions Trust", type: "Fellowship", grantAmount: "₹60,000 / month", region: "Western Ghats", deadline: "January 15, 2027", description: "Documenting tribal bamboo and clay sculpting techniques in forest villages.", requirements: ["4K video gear", "Documentary reel"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Regional Folk Music Recording Residency", organization: "Sangeet Natak Guild", type: "Residency", grantAmount: "₹50,000 / month", region: "Central India", deadline: "February 20, 2027", description: "Field recording unknown regional folk instruments and oral ballads in MP.", requirements: ["Sound engineering skill", "Field gear"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Heritage Architecture Photography Grant", organization: "Monument Preservation Society", type: "Grant", grantAmount: "₹2,00,000", region: "South India Temples", deadline: "March 10, 2027", description: "Architectural photo documentation of 8th-century Chalukya and Chola temple reliefs.", requirements: ["Architectural photography", "High-res portfolio"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Digital Craft Provenance Research Fellowship", organization: "Fair Trade Alliance", type: "Fellowship", grantAmount: "₹55,000 / month", region: "Pan-India", deadline: "April 05, 2027", description: "Developing QR code provenance tags for GI-certified weaving cooperatives.", requirements: ["Research experience", "Supply chain interest"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Folk Art Storytelling & Writing Fellowship", organization: "Riwayat Cultural Press", type: "Fellowship", grantAmount: "₹40,000 / month", region: "Remote / Hybrid", deadline: "May 01, 2027", description: "Writing 20 in-depth longform feature stories on vanishing Indian craft lineages.", requirements: ["Published articles", "Culture reporting"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Oral Tradition Field Audio Fellowship", organization: "Sound Archive India", type: "Fellowship", grantAmount: "₹48,000 / month", region: "Himalayan Region", deadline: "June 15, 2027", description: "Field recording folk songs and spoken narratives in Spiti & Kinnaur.", requirements: ["Audio recording gear", "Himalayan travel"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Traditional Weaving Documentary Commission", organization: "Textile Heritage Trust", type: "Commission", grantAmount: "₹3,00,000", region: "Varanasi & Kanchipuram", deadline: "July 20, 2027", description: "Producing a 30-minute documentary film on gold zari handloom silk weaving.", requirements: ["Short film reel", "Cinematography gear"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Tribal Heritage Documentary Fellowship", organization: "Indigenous Art Forum", type: "Fellowship", grantAmount: "₹52,000 / month", region: "Odisha & Jharkhand", deadline: "August 10, 2027", description: "Documenting Pattachitra palm leaf etchers and Santhal wall mural painters.", requirements: ["Tribal research interest", "Video equipment"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Culinary History Research Grant", organization: "Heritage Foodways Foundation", type: "Grant", grantAmount: "₹1,50,000", region: "Malabar & Chettinad", deadline: "September 05, 2027", description: "Archiving ancient spice blends, brass cookware, and community feast recipes.", requirements: ["Culinary writing", "Field interview skills"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Ancient Temple Architecture Researcher", organization: "Dravidian Heritage Study Group", type: "Fellowship", grantAmount: "₹45,000 / month", region: "Tamil Nadu", deadline: "October 01, 2027", description: "Studying gopuram stone carving proportions and Chola bronze foundry records.", requirements: ["History / Architecture degree"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Craft Cooperative Brand Strategy Grant", organization: "Rural Craft Economy Fund", type: "Grant", grantAmount: "₹2,20,000", region: "Pan-India", deadline: "November 12, 2027", description: "Assisting 5 artisan self-help groups with digital branding and web storefront setup.", requirements: ["Brand strategy", "UI/UX portfolio"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Regional Dance Preservation Fellowship", organization: "Sangeet Research Academy", type: "Fellowship", grantAmount: "₹50,000 / month", region: "Kerala & Manipur", deadline: "December 01, 2027", description: "Video archiving Kathakali and Manipuri Raas Leela ritual performances.", requirements: ["Performance arts background", "Camera gear"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Indigenous Language Oral Archive Grant", organization: "Linguistic Heritage India", type: "Grant", grantAmount: "₹1,75,000", region: "Central India", deadline: "January 20, 2028", description: "Recording oral legends spoken in endangered tribal dialects of Bastar.", requirements: ["Linguistics background", "Audio field kit"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Rural Craft Photojournalist Residency", organization: "Silk Road Photo Trust", type: "Residency", grantAmount: "₹55,000 / month", region: "Kashmir & Punjab", deadline: "February 15, 2028", description: "3-month photojournalism residency documenting Pashmina and Phulkari weavers.", requirements: ["Photojournalism portfolio"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Heritage Tourism Content Creator Fellowship", organization: "Incredible India Creative Lab", type: "Fellowship", grantAmount: "₹65,000 / month", region: "Pan-India", deadline: "March 30, 2028", description: "Creating immersive video travel guides for lesser-known UNESCO heritage sites.", requirements: ["Video editing skills", "Travel vlogging channel"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Folk Instrument Audio Master Grant", organization: "Acoustic Heritage Lab", type: "Grant", grantAmount: "₹2,10,000", region: "Rajasthan Desert", deadline: "April 15, 2028", description: "Recording high-fidelity audio samples of Kamaicha and Sarangi instruments.", requirements: ["Studio quality audio gear", "Folk music love"], link: "https://github.com/Shivsrijit/Riwayat" },
  { title: "Youth Heritage Ambassador Residency", organization: "Riwayat Youth Initiative", type: "Residency", grantAmount: "₹40,000 / month", region: "Pan-India", deadline: "May 10, 2028", description: "Engaging university students to host heritage walks and artisan workshops.", requirements: ["Community organizing", "Social media skills"], link: "https://github.com/Shivsrijit/Riwayat" }
];

async function seedAll() {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/riwayat';
    console.log('[INFO] Attempting database seed connection...');
    await mongoose.connect(MONGO_URI);
    console.log('[SUCCESS] Connected to MongoDB for database seeding!');

    await RecentEvent.deleteMany({});
    await RecentEvent.insertMany(dummyEvents);
    console.log(`[SUCCESS] Seeded ${dummyEvents.length} Recent Events`);

    await FeaturedStory.deleteMany({});
    await FeaturedStory.insertMany(dummyStories);
    console.log(`[SUCCESS] Seeded ${dummyStories.length} Featured Stories`);

    await Destination.deleteMany({});
    await Destination.insertMany(dummyDestinations);
    console.log(`[SUCCESS] Seeded ${dummyDestinations.length} Destinations`);

    await Product.deleteMany({});
    await Product.insertMany(dummyProducts);
    console.log(`[SUCCESS] Seeded ${dummyProducts.length} Artisan Products`);

    await Artist.deleteMany({});
    await Artist.insertMany(dummyArtists);
    console.log(`[SUCCESS] Seeded ${dummyArtists.length} Master Artists`);

    await Workshop.deleteMany({});
    await Workshop.insertMany(dummyWorkshops);
    console.log(`[SUCCESS] Seeded ${dummyWorkshops.length} Workshops`);

    await ForumPost.deleteMany({});
    await ForumPost.insertMany(dummyForumPosts);
    console.log(`[SUCCESS] Seeded ${dummyForumPosts.length} Forum Posts`);

    await CreatorJob.deleteMany({});
    await CreatorJob.insertMany(dummyCreatorJobs);
    console.log(`[SUCCESS] Seeded ${dummyCreatorJobs.length} Creator Jobs & Grants`);

    console.log('[SUCCESS] All 8 collections fully seeded with 20+ authentic items each!');
    mongoose.disconnect();
  } catch (err) {
    console.error('[ERROR] Seeding error:', err.message);
    process.exit(1);
  }
}

seedAll();